/*
 * Databricks
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type ClustersS3StorageInfo struct {
	Destination string `json:"destination,omitempty"`
	Region string `json:"region,omitempty"`
	Endpoint string `json:"endpoint,omitempty"`
	EnableEncryption bool `json:"enable_encryption,omitempty"`
	EncryptionType *ClustersLogS3EncryptionType `json:"encryption_type,omitempty"`
	KmsKey string `json:"kms_key,omitempty"`
	CannedACL string `json:"canned_acl,omitempty"`
}