/* 
 * Databricks
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package models

type ClustersAwsAttributes struct {

	FirstOnDemand int32 `json:"first_on_demand,omitempty"`

	Availability ClustersAwsAvailability `json:"availability,omitempty"`

	ZoneId string `json:"zone_id,omitempty"`

	InstanceProfileArn string `json:"instance_profile_arn,omitempty"`

	SpotBidPricePercent int32 `json:"spot_bid_price_percent,omitempty"`

	EbsVolumeType ClustersEbsVolumeType `json:"ebs_volume_type,omitempty"`

	EbsVolumeCount int32 `json:"ebs_volume_count,omitempty"`

	EbsVolumeSize int32 `json:"ebs_volume_size,omitempty"`
}
