/*
 * Databricks
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package models

type ClustersEditRequest struct {
	NumWorkers int32 `json:"num_workers,omitempty"`

	Autoscale ClustersAutoScale `json:"autoscale,omitempty"`

	ClusterId string `json:"cluster_id,omitempty"`

	ClusterName string `json:"cluster_name,omitempty"`

	SparkVersion string `json:"spark_version,omitempty"`

	SparkConf map[string]string `json:"spark_conf,omitempty"`

	AwsAttributes ClustersAwsAttributes `json:"aws_attributes,omitempty"`

	NodeTypeId string `json:"node_type_id,omitempty"`

	DriverNodeTypeId string `json:"driver_node_type_id,omitempty"`

	SshPublicKeys []string `json:"ssh_public_keys,omitempty"`

	CustomTags map[string]string `json:"custom_tags,omitempty"`

	ClusterLogConf ClustersClusterLogConf `json:"cluster_log_conf,omitempty"`

	SparkEnvVars map[string]string `json:"spark_env_vars,omitempty"`

	AutoterminationMinutes int32 `json:"autotermination_minutes,omitempty"`

	EnableElasticDisk bool `json:"enable_elastic_disk,omitempty"`
}
